# Generated by Django 4.0.6 on 2023-09-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=29)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('about_khadpu', models.TextField()),
                ('facebook', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='text_info',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='static/')),
                ('name', models.CharField(max_length=100)),
                ('info_text', models.TextField()),
            ],
        ),
    ]
